### ISSUE TITLE
Tensorflow, gfx803, `hipErrorNoBinaryForGpu: Unable to find code object for all current devices`

### ISSUE THREAD

**Issue by riaqn** [xuhuisheng/rocm-build#16] opened 2021-08-21 06:59 UTC
### Environment

| Hardware | description   |
|----------|---------------|
| GPU      | RX580            |
| CPU      | 3700X             |

| Software | version |
|----------|---------|
| OS       | Linux 5.13.10       |
| ROCm     | 4.3.0       |
| Python   |  3.9.6    |
| Tensorflow-rocm | 2.5.0 | 

### What is the expected behavior

-Tensorflow should run correctly.

### What actually happens

```
root@darkbox ~# python -m deeporn.fit
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
WARNING:deeporn.model:test_run=True
2021-08-21 08:57:36.488884: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libamdhip64.so
/home/yay/.cache/yay/hip-rocclr/src/HIP-rocm-4.3.0/rocclr/hip_code_object.cpp:486: "hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
fish: Job 1, 'python -m deeporn.fit' terminated by signal SIGABRT (Abort)
```

### How to reproduce

- run any tensorflow program

Do I have to recompile tensorflow?

**Comment by xuhuisheng** [comment] 2021-08-21 07:06
I am not aware that tensorflow-rocm-2.5.0 had been released. I will test it and verify if it support gfx803.

And I have seen you used linux kernel-5.13 and python-3.9. You didn't test under ubuntu-20.04. right?

**Comment by riaqn** [comment] 2021-08-21 07:38
Thanks for the quick reply! I used Arch Linux.

I'm now trying to recompile tensorflow-rocm 2.5.0 using this AUR building script, which supports gfx803. 
https://github.com/rocm-arch/tensorflow-rocm

but encountered some issue:
https://github.com/rocm-arch/tensorflow-rocm/issues/31

**Comment by xuhuisheng** [comment] 2021-08-21 10:46
I recompiled https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/tree/r2.5-rocm-enhanced , and didn't meet your compiling error.

I guess it may be caused by gcc-11, The gcc used in ubuntu-20.04.2 is gcc-9.

**Comment by riaqn** [comment] 2021-08-21 15:38
I'm actually using gcc-11. Let me try gcc-9.

**Comment by xuhuisheng** [comment] 2021-08-21 21:44
Seems only tensorflow-rocm-2.5.0 provided python39 whl.
Maybe you can try python3.8 with tensorflow-rocm-2.4.3 <https://pypi.org/project/tensorflow-rocm/2.4.3/#files>

**Comment by riaqn** [comment] 2021-08-23 07:49
OK, after some research, the problem is that TF-2.5.0 [referencing](https://github.com/tensorflow/tensorflow/blob/v2.5.0/third_party/ruy/workspace.bzl) an outdated version of ruy. The issue in ruy is fixed in later [commit](https://github.com/google/ruy/commit/3c93cda8211efa01128d48950f0d6ee5233c5b9b). TF-2.6.0 references a later version of ruy, which solves the problem.

It seems that TF doesn't backport fixes, meaning we can only wait for tensorflow-rocm 2.6.0, or make a patch according to this [issue](https://github.com/tensorflow/tensorflow/issues/50303)

**Comment by riaqn** [comment] 2021-08-24 08:39
@xuhuisheng I just realize that you mentioned to patch rocblas (removing `library/src/blas3/Tensile/Logic/asm_full/r9nano_*.yaml`). Do we still need to do that for rocm4.3.0?

**Comment by xuhuisheng** [comment] 2021-08-24 09:15
@riaqn 
Please see the document for what this patch doing.
https://github.com/xuhuisheng/rocm-build/tree/master/gfx803#rocm-37-broke-on-gfx803

**Comment by xuhuisheng** [comment] 2021-12-16 12:11
3 months after last posts, I will close this issue, please reopen if there is any updates.

**Closed by xuhuisheng** 2021-12-16 12:11 UTC
